name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: pypi
      url: htps://pypi.org/p/bloom-tui

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up poetry
        run: python -m pip install poetry

      - name: Build the package
        run: poetry build

      - name: Publish dists
        uses: pypa/gh-action-pypi-publish@release/v1
